Please run main.py to get the autoestimator starting
